# Generated by Django 4.0.4 on 2022-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
