# Generated by Django 4.0.4 on 2022-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_perfil_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
