# Generated by Django 4.0.4 on 2022-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_remove_perfilusuario_correo_perfilusuario_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(max_length=200, null=True)),
                ('celular', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
    ]
